name: "Docker image scan"
on: [push]

jobs:
    image-scan:
        runs-on: ubuntu-latest
        steps:
            - name: "Set up Docker Buildx"
              uses: docker/setup-buildx-action@v2
            - name: "Build local container"
              uses: docker/build-push-action@v4
              with:
                tags: ghcr.io/berriai/litellm:main-latest
                push: false
                load: true

            - name: Scan image
              uses: anchore/scan-action@v3
              with:
                image: "ghcr.io/berriai/litellm:main-latest"