name: Extract Issue Form Values

on:
  issues:
    types:
      - opened

jobs:
  extract-values:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Issue Form Data
        run: |
          ISSUE_BODY="${{ github.event.issue.body }}"
          echo "Issue Body: $ISSUE_BODY"
          
          FIELD_1=$(echo "$ISSUE_BODY" | grep -A1 '### Aplicacion' | tail -n1 | xargs)
          FIELD_2=$(echo "$ISSUE_BODY" | grep -A1 '### Tipo de aplicacion' | tail -n1 | xargs)
          
          echo "FIELD_1=$FIELD_1" >> $GITHUB_ENV
          echo "FIELD_2=$FIELD_2" >> $GITHUB_ENV
          
      - name: Print Extracted Values
        run: |
          echo "Extracted Field 1: $FIELD_1"
          echo "Extracted Field 2: $FIELD_2"
