name: Project Item Moved Tracking

on:
  github-event-name: 'projects_v2_item_moved'

jobs:
  track-item-movement:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      projects: read
    steps:
      - name: Log Project Item Movement
        env:
          EVENT_PAYLOAD: ${{ toJson(github.event) }}
        run: |
          echo "Project item moved"
          echo "Payload details: $EVENT_PAYLOAD"
          
      - name: Extract Movement Details
        env:
          EVENT_PAYLOAD: ${{ toJson(github.event) }}
        run: |
          echo "Project ID: $(echo '$EVENT_PAYLOAD' | jq '.project_id')"
          echo "Previous Column: $(echo '$EVENT_PAYLOAD' | jq '.changes.column_id.from')"
          echo "Current Column: $(echo '$EVENT_PAYLOAD' | jq '.project_id')"
